sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  on_failure: change
node_js:
  - "5"
before_script:
  - npm prune
script: npm test && cd demo && npm i && PUBLIC_PATH=/cv npm run build
after_success:
  - bash ./deploy-gh-pages.sh
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
